# PostgreSQL. Versions 9.3 and up are supported.

development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: piscinasmg
  encoding: unicode
  host: localhost
  username: pguser
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
